services:
  engine:
    container_name: engine
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${CORE_PORT:-80}:${CORE_PORT:-80}"
    environment:
      - CORE_PORT=${CORE_PORT:-80}
    command: uvicorn dataherald.app:app --host 0.0.0.0 --port ${CORE_PORT:-80} --log-config log_config.yml --log-level debug --reload
    stdin_open: true
    tty: true
    volumes:
      - ./dataherald:/app/dataherald
    networks:
      - dataherald_network
    env_file: .env
# uncomment if you want to use the s3 alternative minio instead of AWS S3
# you need to setup a bucket in the web interface (http://localhost:9001)
#  minio:
#    container_name: s3
#    image: minio/minio
#    networks:
#      - dataherald_network
#    ports:
#      - "9000:9000"
#      - "9001:9001"
#    volumes:
#      - ./s3data:/data
#    environment:
#      MINIO_ROOT_USER: "${MINIO_ROOT_USER:-dataherald}"
#      MINIO_ROOT_PASSWORD: "${MINIO_ROOT_PASSWORD:-dataherald"}
#    command: server --console-address ":9001" /data
networks:
  dataherald_network:
    external: true
